name: barcode_scan2
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 4.3.0

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0

dev_dependencies:
  pedantic_mono: ^1.26.0

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: de.mintware.barcode_scan
        pluginClass: BarcodeScanPlugin
      ios:
        pluginClass: BarcodeScanPlugin
